### PR TITLE
A fix for not using multiple languages

### PR DESCRIPTION
**Pull request by android-1995**

### CODE REVIEW

**Comment by K11MCH1** [comment]
If you're offering a fix for something, contact the devs on Discord first.
Otherwise issues do not belong here.

**Comment by android-1995** [comment]
Okay, I'm not comfortable using Discord. Can you give me feedback on this issue?

**Comment by K11MCH1** [comment]
> OK, I can't use Discord. Can you help me contact the devs on Discord with this if you can?

Post your issue here https://github.com/skyline-emu/skyline/issues
Please explain in details what your issue is. The devs will notice.

**Comment by PixelyIon** [comment]
We do actually accept fixes on GitHub for minor issues but in this case I don't quite understand what this PR is fixing and how it manages to fix it. The changes don't quite make sense.

**Comment by android-1995** [comment]
> We do actually accept fixes on GitHub for minor issues but in this case I don't quite understand what this PR is fixing and how it manages to fix it. The changes don't quite make sense.

image
These two places are not using multiple languages

**Pull request closed without merging**
