### PR TITLE
Add a delete button to the game dialog

### PR DESCRIPTION
**Pull request by AbandonedCart**
Bear with me because there is some stuff that would normally be unnecessary, but needs to be included because of timing.

This adds the ability to delete a file through the game dialog. The problem, as you may already know, is that write permission is not being requested to display the game list. That is why this has to check for write permission to be present and then call a new instance of selecting your root folder to add it. By doing it this way and not simply trying to shoehorn write permission on top of the existing request, it prevents ever having to request it again for subsequent files. As for new requests (ie. new installs), the permission will be requested as part of the initial setup. I'm sure there are 100 prettier ways to go about this, but most would involve having requested the write permission up front, despite not needing it yet.

Oh, and the delete button is intentionally the negative button to prevent accidental presses. Anyone rushing through dialogs should end up cancelling, not deleting files.

### CODE REVIEW

**Comment by Ragul32** [comment]
Add screenshot with comments it will be useful

**Comment by AbandonedCart** [comment]
> Add screenshot with comments it will be useful

Of the delete button or the file being there and then not?

**Comment by Ragul32** [comment]
> > Add screenshot with comments it will be useful
> 
> Of the delete button or the file being there and then not?

Like showing delete button with dialog box that's all

**Comment by AbandonedCart** [comment]
> Like showing delete button with dialog box that's all

They aren't displayed at the same time.

<details>
<summary>Delete button</summary>

delete
</details>

<details>
<summary>Delete dialog</summary>

dialog
</details>

As you can see, they are pretty straightforward.

**Comment by lynxnb** [comment]
I can't see any valid use-case for this honestly. Deleting a game would be something we can easily delegate to file manager, which doesn't need UI elements on our end. Did you have any specific need that brought you to implement this?

**Comment by AbandonedCart** [comment]
> Did you have any specific need that brought you to implement this?

https://github.com/skyline-emu/skyline/issues/2218

As it stands, you open the emulator, play a game, decide you don't want it, quit the emulator, open a file manager, find the file, and delete the file.

With the basic functionality there, it can also be wired to the home screen icon so when you decide to remove a game, you actually have the option to delete the entire game and not delete the icon, open a file manager, find the file, and delete the file.

Seems like delegating it to a file manager would be a way to avoid the need to write the code for it, but I did that.

**Comment by AbandonedCart** [comment]
The home icon will be a circus, by the way. It would give this more context, but it's one of those things where only system apps have really used it and the documentation is more or less "make an xml and click your heels" but then nothing happens. I have surgery in the morning tomorrow, so hopefully I can put something together after that.

**Comment by lynxnb** [comment]
As I understand #2218 was about having an icon to delete saves/pipeline cache/whatnot in the future, not about deleting the game ROM. There's no reason to expose an option to delete game ROMs in the emulator, for this reason I'm going to close this.

**Comment by AbandonedCart** [comment]
It does make removing old games a lot easier, but it's also perfectly acceptable to _prefer_ not having the option.

As for 2218, it read like it was about deleting **everything**. The game, any shortcuts to it, the cache, saves, and anything else even remotely related. Some of it is flat out impossible because you can't delete, only disable, shortcuts created through the pin method and media captured outside the app only, at best, is named for the app in which it was taken.

Attaching the cache to removing a game from the library is probably the only realistic option left, if it isn't removed already. I don't know about you, but if deleting a game to free up space removed my save, I'd be pissed. Settings can already be cleared, but they aren't significant enough to justify removing them and would likely just need to be set the same way if the game ever returned.

**Pull request closed without merging**
