### PR TITLE
Adding game compatibility to README.md

### PR DESCRIPTION
**Pull request by bleszerd**
Adding skyline-games-list repo issues to README.md

### CODE REVIEW

**Comment by bleszerd** [comment]
I noticed that many users arrive on this page and go to discord to ask if there is a game compatibility list, thinking about it I believe that having a direct link to the problems in the other repository is good

**Comment by bylaws** [comment]
Good idea

**Comment by Abdul78690** [comment]
Implement snapdragon 720g,730g and other 7th series also in skyline emulator,in this new update i can't able to open any roms,in before update cuphead is playable but sometimes loading stages will pick black screen and not rom works after black screen, please add Pokemon games i eagerly waiting for this

**Comment by PixelyIon** [comment]
This has been superseded by https://github.com/skyline-emu/skyline/commit/517f92fd1c5608a6226707784aac378e408ed7fb, you've been added as a co-author.

**Pull request closed without merging**
