### PR TITLE
Add an option to filter valid files for library

### PR DESCRIPTION
**Pull request by AbandonedCart**
I don't know if this is the case for everyone, but I store DLC and stuff alongside my games in a folder named after the game. This means that when I load the emulator, my list of items is like 30 long, but only 6 of them are games. Filtering the files shouldn't be enforced, but having the option would be nice. For now, it's based on a version being populated, since none of the DLC are actually assigned versions read by the emulator.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Yeah, so changing the name of the preference mid commit wasn't the best idea...

**Comment by AbandonedCart** [comment]
<details>
<summary>Filter Off</summary>

filter_off
</details>

<details>
<summary>Filter On</summary>

filter_on
</details>

**Comment by bylaws** [comment]
idk if i'm a fan of this, it feels like something better solved on a user side, @lynxnb thoughts?

**Comment by AbandonedCart** [comment]
Oh, and to be fair, I'm not fond of it. It feels a bit hacky. I'm not denying that at all.

**Comment by AbandonedCart** [comment]
Closing in favor of a more rational alternative

**Pull request closed without merging**
