### PR TITLE
Add rating organizations informations

### PR DESCRIPTION
**Pull request by KikiManjaro**
Add rating organizations informations like PEGI, ESRB, CERO etc.

Add a new preference to choose which organization to display from.

Only displaying the info in game info.

Here are some screenshot

<details><summary>Screenshots</summary>
<p>

Screenshot_2023-04-02-15-56-18-811_skyline emu dev
Screenshot_2023-04-02-15-56-01-227_skyline emu dev
Screenshot_2023-04-02-15-56-04-921_skyline emu dev
Screenshot_2023-04-02-15-56-12-816_skyline emu dev
Screenshot_2023-04-02-15-55-52-166_skyline emu dev

</p>
</details> 

It's the second time ever i'm working with c++, i could have made some mistakes, sorry. Feel free to let me know if i could improve anything :)

### CODE REVIEW

**Comment by AbandonedCart** [comment]
I had no idea that was actually stored in the file. I guess it makes sense for how consoles can block games, though. That's pretty neat.

**Comment by KikiManjaro** [comment]
> I had no idea that was actually stored in the file. I guess it makes sense for how consoles can block games, though. That's pretty neat.

Thanks :) I found this while looking at this : https://switchbrew.org/wiki/NACP
There is a lot of information stored in the file, maybe there is more that can be useful.

**Comment by lynxnb** [comment]
I fear this is going to make the dialog overflow/clutter up really badly on smaller devices when portrait.

**Comment by bylaws** [comment]
Tbh I'm not sure this is desired considering this code will maybe be rewritten soon for new VFS

**Pull request closed without merging**
