### PR TITLE
Android 8 Compatibility

### PR DESCRIPTION
**Pull request by Kawata0210**
Add android 8 compatibility for Older device can use Skyline™

### CODE REVIEW

**Comment by PixelyIon** [comment]
We will never be adding Android 8 support, most devices that are on Android 8 will not be able to run Skyline regardless.

**Comment by SpyroGam3r** [comment]
Buy a phone with Android 10 eta when :trollface:

**Comment by mateoalfaro** [comment]
> Buy a phone with Android 10 eta when :trollface:

Accept android 9 superiority when smh

**Comment by nekomekoraiyuu** [comment]
Bro just use a damn gsi
(Instant mali profit) :jefftrollo:

**Comment by Levella2000** [comment]
does not work on android 9

**Pull request closed without merging**
