### PR TITLE
Add fliphone support

### PR DESCRIPTION
**Pull request by Ojerty89617**
Adds support for poco

### CODE REVIEW

**Comment by 2Tsk2** [comment]
Please do not post troll or useless PR's or you will be blocked from the repo, thank you.

**Comment by proganime1200** [comment]
definitely a egg ns supporter

**Comment by raiyuulmao** [comment]
We have added sapport for brick now sar!!!
Click here to claim your skyline emulador brick

**Comment by raiyuulmao** [comment]
popo supporder Moment

**Pull request closed without merging**
