### PR TITLE
Update BUILDING.md

### PR DESCRIPTION
**Pull request by HERCULESxp**
ndk path windows  to add into local.propertes

### CODE REVIEW

**Comment by mjcox244** [comment]
Unfortunately this update to the guide will not work for anyone with a user account not called "skyline"

**Comment by finr0y** [comment]
if you change it to %USERPROFILE% i think it can work for anyone

**Comment by HERCULESxp** [comment]
I put it in the same way as above with Linux, but using the %USERPROFILE% It's the best way.

**Comment by mjcox244** [comment]
> I put it in the same way as above with Linux, but using the %USERPROFILE% It's the best way.

that's a point actually, why isn't it using "$HOME"

**Comment by HERCULESxp** [comment]
what would the path be like in linux? It would be like this: ```properties
ndk.dir=/$HOME/opt/android-sdk/ndk/25.0.8221429
```

**Comment by bylaws** [comment]
ndk.dir is deprecated and should not be used

**Comment by AbandonedCart** [comment]
https://github.com/skyline-emu/skyline/commit/adba8c52c067d0c495e5f796b41071ea2ac0fb10 is a bit misleading.

Linux should be $HOME, while Mac is ~, and Windows is %USERPROFILE% but it doesn't specify a platform and follows an example given for Windows.

**Pull request closed without merging**
