### PR TITLE
Comma splices in ReadMe

### PR DESCRIPTION
**Pull request by JustAHippo**
Very important fix to skyline. I feel this degrades performance by 10000%

### CODE REVIEW

**Comment by pizza-10** [comment]
What?

**Comment by BIGD15** [comment]
> What? Do you mean that the emulator will now support graphics?

Always been 🔫

**Comment by SD9779** [comment]
No not yet but skyline are working on it

**Comment by PixelyIon** [comment]
This is too minor and not something most people even recognize as an error.

**Pull request closed without merging**
