### PR TITLE
Add Chinese text

### PR DESCRIPTION
**Pull request by neighbor-bear**
Added some Chinese text, hoping to add it to the simulator

### CODE REVIEW

**Comment by QuackingCanary** [comment]
Thanks for your time and your participation. Languages will be added afterwards. Check GitHub issues, you'll find a "GUI Translations" thread where you can apply to submit your translations.

**Comment by neighbor-bear** [comment]
> Thanks for your time and your participation. Languages will be added afterwards. Check GitHub issues, you'll find a "GUI Translations" thread where you can apply to submit your translations.

Thank you for your reply. In fact, this is my first time to submit a project, so I'm not familiar with it

**Comment by Thepowa753** [comment]
https://github.com/skyline-emu/skyline/pull/1136#issuecomment-1113250495

**Comment by 2Tsk2** [comment]
While we appreciate translation submissions such as this, a better system for delivering translations from the community is being planned in the future, I will be closing this PR for this reason, I hope you understand and have a good day.

**Pull request closed without merging**
