### PR TITLE
Let's go Pikachu crashes on SD 710

### PR DESCRIPTION
**Pull request by LittleUxie10**
Need fix for Pokemon let's go Pikachu .

### CODE REVIEW

**Comment by KYM201** [comment]
Exellent

**Comment by Thepowa753** [comment]
FUCKING STOP.

**Comment by MrSinghG** [comment]
How to download emulater ??

**Comment by MrSinghG** [comment]
And how to download

**Comment by josesilveiraa** [comment]
Stop creating endless PRs with dumb issues like this one. You know that the emulator isn't even in its beta stage, and probably it'll never reach "stable" status like every emulator nowadays. Fucking stop it. It's because people like you that the devs will stop the development.

**Comment by PixelyIon** [comment]
@josesilveiraa While we do find these a tad bit annoying, it's more on GitHub's UI/UX rather than anything else. Not everyone is tech-savvy and that's fine, it's nothing we would ever stop the project over.

**Pull request closed without merging**
