### PR TITLE
Remove header rom filter (append)

### PR DESCRIPTION
**Pull request by AbandonedCart**
This is the extension of #2295 discussed in that PR

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Does the sorting itself stay as an option or should that be stripped?

**Comment by lynxnb** [comment]
IMO, we get rid of it. Has it been any useful to anyone ever?

**Comment by lynxnb** [comment]
Also I quickly glanced at the code, and I can say for sure that much more can be done in removing the filtering code. We load roms in a per-format map in `RomProvider.kt`, that should go as well.

**Comment by AbandonedCart** [comment]
Removing anything else was waiting on the previous decision because a lot of it was tied to the sorting. There would have been no point trying to retain the sorting and then end up removing it anyway.

**Comment by AbandonedCart** [comment]
That last one could be replaced with actually setting the serialVersionUID, but I wasn't sure how you wanted to come up with the value.

**Comment by lynxnb** [comment]
SerialVersionUID doesn't matter for `AppItem` so it's fine just silencing the warning. I'll be reviewing the rest soon. Have you tried running the app and seeing if it works? Remember to try with a clean install of skyline too.

**Review by lynxnb — APPROVED** [review]
LGTM, great job, also to @dima-xd!
As a side note, for future reference, you don't need to remove strings from all languages, that is done automatically by Transifex when we sync translations. You only need to remove them from the main `strings.xml`.

**Comment by AbandonedCart** [comment]
I just realized I never answered. Yes, I tested it. The one issue I found is in the PR for obscure crashes

**Comment by Sugiyaro** [comment]
Huss

**Pull request merged**
