### PR TITLE
Stub `ectx:w` and `ectx:aw` Glue services

### PR DESCRIPTION
**Pull request by lynxnb**
See commit description and linked issue.

### CODE REVIEW

**Comment by PibePlayer** [comment]
I think this should be merged to ftx1 instead of master, since that's where the Development being made

**Comment by NotAWeeb69** [comment]
> I think this should be merged to ftx1 instead of master, since that's where the Development being made

Smh thats not how it works. Its easier to work on a bigger ammount of branches to add new features. Simply it would get messy if youd mash stuff into one branch

**Comment by PibePlayer** [comment]
> > I think this should be merged to ftx1 instead of master, since that's where the Development being made
> 
> Smh thats not how it works. Its easier to work on a bigger ammount of branches to add new features. Simply it would get messy if youd mash stuff into one branch

Of course, but the ftx1 branch is the one that has graphics support. I did want to try this for some games but I'll need to merge locally the commits to the ftx1 and build it to test now :P

**Comment by jduncanator** [comment]
The PR should be merged to (targeting) master. Once it's accepted and merged, ftx1 will be rebased on master to pull in the latest changes.

**Comment by lynxnb** [comment]
It should now be correctly stubbed.

**Review by PixelyIon — APPROVED** [review]
LGTM!

**Pull request merged**
